// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xbWc-Ou3SJkgb6hCNc6Wsz-QmlenVZQ',
    appId: '1:642697276714:web:e1dbe927da488fa3c08253',
    messagingSenderId: '642697276714',
    projectId: 'home-food-marketplace-5a60f',
    authDomain: 'home-food-marketplace-5a60f.firebaseapp.com',
    storageBucket: 'home-food-marketplace-5a60f.firebasestorage.app',
    measurementId: 'G-1F3Q6H4HQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCn3As_8t9qVfCSl1xmh0GiZgTaPMnW8E',
    appId: '1:642697276714:android:a0d996794335dfd2c08253',
    messagingSenderId: '642697276714',
    projectId: 'home-food-marketplace-5a60f',
    storageBucket: 'home-food-marketplace-5a60f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oaBpXkwl__0y8yyJ_HuWHeurQ1jeqMs',
    appId: '1:642697276714:ios:1fca648df0a54840c08253',
    messagingSenderId: '642697276714',
    projectId: 'home-food-marketplace-5a60f',
    storageBucket: 'home-food-marketplace-5a60f.firebasestorage.app',
    iosBundleId: 'com.example.homeFoodMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0oaBpXkwl__0y8yyJ_HuWHeurQ1jeqMs',
    appId: '1:642697276714:ios:1fca648df0a54840c08253',
    messagingSenderId: '642697276714',
    projectId: 'home-food-marketplace-5a60f',
    storageBucket: 'home-food-marketplace-5a60f.firebasestorage.app',
    iosBundleId: 'com.example.homeFoodMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5xbWc-Ou3SJkgb6hCNc6Wsz-QmlenVZQ',
    appId: '1:642697276714:web:bc80a2452c861651c08253',
    messagingSenderId: '642697276714',
    projectId: 'home-food-marketplace-5a60f',
    authDomain: 'home-food-marketplace-5a60f.firebaseapp.com',
    storageBucket: 'home-food-marketplace-5a60f.firebasestorage.app',
    measurementId: 'G-MT4NVBXDNR',
  );
}
